image: quay.io/dolfinadjoint/dev-dolfin-adjoint

pipelines:
  default:
    - step:
        script:
          - pip2 install --no-cache-dir --upgrade pytest
          - export HOME=/home/fenics
          - export FENICS_PREFIX=$HOME/local
          - export FENICS_PYTHON_MAJOR_VERSION=2
          - export FENICS_PYTHON_MINOR_VERSION=7
          - source /home/fenics/.profile
          - source /home/fenics/dolfin-adjoint.conf
          - update_libadjoint
          - cd $BITBUCKET_CLONE_DIR
          - pip2 install --no-cache-dir --upgrade --prefix=$FENICS_PREFIX .
          - python2 -m pytest -v test
